/**
 * `weeek completion <shell>` — shell completion generated from the same registry as the
 * commands themselves, so it can never drift out of sync with what actually exists.
 */

import { Command } from 'commander'
import { WeeekError } from '../core/api/errors.ts'

type Shell = 'bash' | 'zsh' | 'fish'

interface Node {
  name: string
  children: Map<string, Node>
  flags: string[]
  summary: string
}

const EXTRA_COMMANDS = [
  { path: ['auth', 'login'], summary: 'store an API token' },
  { path: ['auth', 'status'], summary: 'show the active token source' },
  { path: ['auth', 'logout'], summary: 'remove a stored token' },
  { path: ['doctor'], summary: 'check configuration and connectivity' },
  { path: ['schema'], summary: 'print the command registry' },
  { path: ['api'], summary: 'send a raw API request' },
  { path: ['ui'], summary: 'interactive kanban board' },
  { path: ['completion'], summary: 'generate shell completion' },
]

async function buildTree(): Promise<Node> {
  const { OPERATIONS } = await import('../core/api/generated/operations.ts')
  const root: Node = { name: 'weeek', children: new Map(), flags: [], summary: '' }

  const insert = (path: readonly string[], summary: string, flags: string[]) => {
    let node = root
    for (const segment of path) {
      let child = node.children.get(segment)
      if (!child) {
        child = { name: segment, children: new Map(), flags: [], summary: '' }
        node.children.set(segment, child)
      }
      node = child
    }
    node.summary = summary
    node.flags = flags
  }

  for (const op of OPERATIONS) {
    const flags = op.params.filter((p) => p.in === 'query').map((p) => `--${p.cli}`)
    for (const field of op.body?.fields ?? []) flags.push(`--${field.cli}`)
    insert(op.command, op.summary, flags)
  }
  for (const extra of EXTRA_COMMANDS) insert(extra.path, extra.summary, [])

  return root
}

function flatten(node: Node, prefix: string[] = []): { path: string[]; node: Node }[] {
  const here = prefix.length > 0 ? [{ path: prefix, node }] : []
  return [...here, ...[...node.children.values()].flatMap((c) => flatten(c, [...prefix, c.name]))]
}

const GLOBAL_FLAGS = [
  '--profile',
  '--token-file',
  '--config-dir',
  '--base-url',
  '--output',
  '--json',
  '--no-color',
  '--quiet',
  '--verbose',
  '--yes',
  '--dry-run',
  '--help',
  '--version',
]

function bashScript(entries: { path: string[]; node: Node }[]): string {
  const cases = entries
    .map(({ path, node }) => {
      const children = [...node.children.keys()].join(' ')
      const words = [children, ...node.flags].filter(Boolean).join(' ')
      return `    "${path.join(' ')}") __weeek_reply "${words}" ;;`
    })
    .join('\n')

  const roots = entries
    .filter((e) => e.path.length === 1)
    .map((e) => e.path[0])
    .join(' ')

  return `# weeek bash completion — generated by \`weeek completion bash\`
_weeek() {
  local cur prev line
  cur="\${COMP_WORDS[COMP_CWORD]}"
  line="\${COMP_WORDS[*]:1:COMP_CWORD-1}"

  __weeek_reply() { COMPREPLY=( $(compgen -W "$1 ${GLOBAL_FLAGS.join(' ')}" -- "$cur") ); }

  case "$line" in
${cases}
    *) __weeek_reply "${roots}" ;;
  esac
}
complete -F _weeek weeek
`
}

function zshScript(entries: { path: string[]; node: Node }[]): string {
  const cases = entries
    .map(({ path, node }) => {
      const children = [...node.children.values()]
        .map((c) => `'${c.name}:${c.summary.replace(/'/g, '')}'`)
        .join(' ')
      const flags = node.flags.map((f) => `'${f}'`).join(' ')
      return `    "${path.join(' ')}")\n      _values 'option' ${children} ${flags} ;;`
    })
    .join('\n')

  const roots = entries
    .filter((e) => e.path.length === 1)
    .map((e) => `'${e.path[0]}:${e.node.summary.replace(/'/g, '')}'`)
    .join(' ')

  return `#compdef weeek
# generated by \`weeek completion zsh\`
_weeek() {
  local line="\${words[2,CURRENT-1]}"
  case "$line" in
${cases}
    *) _values 'command' ${roots} ;;
  esac
}
compdef _weeek weeek
`
}

function fishScript(entries: { path: string[]; node: Node }[]): string {
  const lines: string[] = ['# generated by `weeek completion fish`']

  for (const { path, node } of entries) {
    const description = node.summary.replace(/'/g, '')
    const condition =
      path.length === 1
        ? '__fish_use_subcommand'
        : `__fish_seen_subcommand_from ${path.slice(0, -1).join(' ')}`
    lines.push(`complete -c weeek -f -n '${condition}' -a '${path.at(-1)}' -d '${description}'`)
    for (const flag of node.flags) {
      lines.push(
        `complete -c weeek -n '__fish_seen_subcommand_from ${path.join(' ')}' -l '${flag.replace(/^--/, '')}'`,
      )
    }
  }

  for (const flag of GLOBAL_FLAGS) {
    lines.push(`complete -c weeek -l '${flag.replace(/^--/, '')}'`)
  }

  return `${lines.join('\n')}\n`
}

export function completionCommand(): Command {
  return new Command('completion')
    .description('generate a shell completion script')
    .argument('<shell>', 'bash, zsh or fish')
    .addHelpText(
      'after',
      '\nExamples:\n' +
        '  weeek completion zsh  > ~/.zfunc/_weeek\n' +
        '  weeek completion bash > /etc/bash_completion.d/weeek\n' +
        '  weeek completion fish > ~/.config/fish/completions/weeek.fish\n',
    )
    .action(async (shell: string) => {
      const tree = await buildTree()
      const entries = flatten(tree)

      switch (shell as Shell) {
        case 'bash':
          process.stdout.write(bashScript(entries))
          return
        case 'zsh':
          process.stdout.write(zshScript(entries))
          return
        case 'fish':
          process.stdout.write(fishScript(entries))
          return
        default:
          throw new WeeekError({
            kind: 'input',
            message: `Unsupported shell "${shell}". Use bash, zsh or fish.`,
          })
      }
    })
}
